import importlib

turbogator_ext = importlib.import_module("turbogator.turbogator_ext")

# baseline impl
equi_linear_baseline = turbogator_ext.equi_linear_baseline
equi_linear_opt_v2 = turbogator_ext.equi_linear_opt_v2
geometric_product_baseline = turbogator_ext.geometric_product_baseline
geometric_product_opt_v1 = turbogator_ext.geometric_product_opt_v1
equi_join_baseline = turbogator_ext.equi_join_baseline
equi_join_optimized_hardcoded = turbogator_ext.equi_join_optimized_hardcoded
equi_join_optimized_avx2 = turbogator_ext.equi_join_optimized_avx2
equi_join_optimized_sparse = turbogator_ext.equi_join_optimized_sparse
equi_join_optimized_precompute_ab = turbogator_ext.equi_join_optimized_precompute_ab
equi_join_optimized_unroll_k = turbogator_ext.equi_join_optimized_unroll_k
equi_join_restrict_unswitch = turbogator_ext.equi_join_restrict_unswitch
equi_rms_norm_baseline = turbogator_ext.equi_rms_norm_baseline
equi_rms_norm_branchless_clamp = turbogator_ext.equi_rms_norm_branchless_clamp
equi_rms_norm_restrict = turbogator_ext.equi_rms_norm_restrict
equi_rms_norm_unrolled_selector = turbogator_ext.equi_rms_norm_unrolled_selector
equi_rms_norm_reciprocal_div = turbogator_ext.equi_rms_norm_reciprocal_div
equi_rms_norm_prefetch = turbogator_ext.equi_rms_norm_prefetch
equi_rms_norm_unrolled_channels_4 = turbogator_ext.equi_rms_norm_unrolled_channels_4
equi_rms_norm_assume_aligned = turbogator_ext.equi_rms_norm_assume_aligned
equi_rms_norm_combined = turbogator_ext.equi_rms_norm_combined
scaler_gated_gelu_baseline = turbogator_ext.scaler_gated_gelu_baseline
equi_geometric_attention_baseline = turbogator_ext.equi_geometric_attention_baseline
equi_geometric_attention_optimized1 = turbogator_ext.equi_geometric_attention_optimized1
equi_geometric_attention_optimized2 = turbogator_ext.equi_geometric_attention_optimized2

# vectorized impl
geometric_product_vectorized = turbogator_ext.geometric_product_vectorized
