import importlib

turbogator_ext = importlib.import_module("turbogator.turbogator_ext")

# geometric product
geometric_product_baseline = turbogator_ext.geometric_product_baseline
geometric_product_opt_v1 = turbogator_ext.geometric_product_opt_v1
geometric_product_vectorized = turbogator_ext.geometric_product_vectorized
geometric_product_vectorized_out = turbogator_ext.geometric_product_vectorized_out

# equi_join
equi_join_baseline = turbogator_ext.equi_join_baseline
equi_join_opt_v1 = turbogator_ext.equi_join_opt_v1
equi_join_opt_v2 = turbogator_ext.equi_join_opt_v2
equi_join_vectorized = turbogator_ext.equi_join_vectorized
equi_join_vectorized_out = turbogator_ext.equi_join_vectorized_out

# equi_geometric_attention
equi_geometric_attention_baseline = turbogator_ext.equi_geometric_attention_baseline
equi_geometric_attention_opt_v1 = turbogator_ext.equi_geometric_attention_opt_v1
equi_geometric_attention_vectorized = turbogator_ext.equi_geometric_attention_vectorized

# scaler_gated_gelu
scaler_gated_gelu_baseline = turbogator_ext.scaler_gated_gelu_baseline
scaler_gated_gelu_vectorized = turbogator_ext.scaler_gated_gelu_vectorized

# // equi_linear
equi_linear_baseline = turbogator_ext.equi_linear_baseline
equi_linear_opt_v1 = turbogator_ext.equi_linear_opt_v1
equi_linear_opt_v2 = turbogator_ext.equi_linear_opt_v2
equi_linear_vectorized = turbogator_ext.equi_linear_vectorized

# // equi_rms_norm
equi_rms_norm_baseline = turbogator_ext.equi_rms_norm_baseline
equi_rms_norm_opt_v1 = turbogator_ext.equi_rms_norm_opt_v1
equi_rms_norm_vectorized = turbogator_ext.equi_rms_norm_vectorized
